theme: jekyll-theme-cayman
title: <div align="center">Titan Simulation Library</div>
head_title: Titan Simulation Library
show_downloads: true
release_url: https://github.com/jacobaustin123/Titan/releases
